debug: true
spring:
  application:
    name: gateway

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

zuul:
  routes:
    admin:
      path: /admin/**
#    employee:
#      path: /employee/**
#    organization:
#      path: /organization/**