#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: admin-v1
##  labels:
##    app: admin
##   version: admin-v1
#spec:
#  selector:
#    matchLabels:
#      app: admin
#      version: v1
#  template:
#    metadata:
##      annotations:
##        sidecar.istio.io/inject: "true"
#      labels:
#        app: admin
#        version: v1
#    spec:
#      containers:
#        - name: admin
#          image: samwandocker/jobsapp:jobs-admin # jobs/admin:1.0 #samwandocker/jobsapp:admin #
#          imagePullPolicy: Always
#          ports:
#            - containerPort: 8080
#          env:
#            - name: VERSION
#              value: "v1"
#      imagePullSecrets:
#        - name: regcred
#
#---

#---
#kind: ConfigMap
#apiVersion: v1
#metadata:
#  name: admin
#data:
#  application.yml: |-
#    spring:
#     cloud:
#      kubernetes:
#        discovery:
#          all-namespaces: true
#          service-labels:
#            spring-boot: true
---
apiVersion: v1
kind: Service
metadata:
  name: jobs-admin-service
  labels:
    app: jobs-admin-service
    service: jobs-admin-service
spec:
#  type: NodePort
  selector:
    app: jobs-admin-service
  ports:
    - name: http
      port: 8080
#      protocol: TCP
#      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jobsapp-admin
  labels:
    account: jobs-admin-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobs-admin-service-v1
  labels:
    app: jobs-admin-service
    version: jobs-admin-service-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobs-admin-service
      version: v1
  template:
    metadata:
      labels:
        app: jobs-admin-service
        version: v1
    spec:
      serviceAccountName: jobs-admin-service
      containers:
      - name: jobs-admin-service
        image: samwandocker/jobsapp:jobs-admin-service # jobs/admin:1.0 #samwandocker/jobsapp:admin #
        imagePullPolicy: IfNotPresent
        env:
          - name: JOBS_ADMIN_SERVICE_DB_HOST
            value: jobs-admin-service-mysql
          - name: JOBS_ADMIN_SERVICE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-pass
                key: password
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
      volumes:
      - name: tmp
        emptyDir: {}
      imagePullSecrets:
          - name: regcred
---